

package reglas;


public class Regla2 {
    
    /*REGLA 2: TODA CLASE TIENE COMO MINIMO EL CONSTRUCTOR DE DEFECTO
    */
    

public Regla2(){ /*ESTE ES EL CONSTRUCTOR POR DEFECTO */

    /* TODAS LAS CLASES TIENE EL CONSTRUCTOR POR DEFECTO, A VECES SE CREAN AUTOMATICAMENTE, PERO
    PODEMOS CREARLOS NOSOTROS TAMBIEN SI NO SE HUBIERAN CREADO AUTOMATICAMENTE
    */
    
    }
    


}
